-- Generated by the tools.  DO NOT EDIT!
_G.CPP_TABLE_PROTO = _G.CPP_TABLE_PROTO or {}
_G.CPP_TABLE_PROTO.Player = {
    name = { type = "normal", key = "string", tag = 1, size = 8 },
    score = { type = "normal", key = "int32", tag = 2, size = 4 },
    is_vip = { type = "normal", key = "bool", tag = 3, size = 1 },
    experience = { type = "normal", key = "float", tag = 4, size = 4 },
    items = { type = "array", key = "Item", tag = 5, size = 8 },
    labels = { type = "array", key = "int32", tag = 6, size = 8 },
    pet = { type = "normal", key = "Pet", tag = 7, size = 8 },
    friends = { type = "map", key = "string", value = "Friend", tag = 8, size = 8 },
    params = { type = "map", key = "int32", value = "int32", tag = 9, size = 8 },
}
_G.CPP_TABLE_PROTO.Item = {
    id = { type = "normal", key = "int64", tag = 1, size = 8 },
    name = { type = "normal", key = "string", tag = 2, size = 8 },
    price = { type = "normal", key = "int32", tag = 3, size = 4 },
}
_G.CPP_TABLE_PROTO.Pet = {
    name = { type = "normal", key = "string", tag = 1, size = 8 },
    age = { type = "normal", key = "int32", tag = 2, size = 4 },
    breed = { type = "normal", key = "string", tag = 3, size = 8 },
    weight = { type = "normal", key = "double", tag = 4, size = 8 },
}
_G.CPP_TABLE_PROTO.Friend = {
    name = { type = "normal", key = "string", tag = 1, size = 8 },
    age = { type = "normal", key = "int32", tag = 2, size = 4 },
    email = { type = "normal", key = "string", tag = 3, size = 8 },
}
