-- Generated by the tools.  DO NOT EDIT!
_G.CPP_TABLE_PROTO = _G.CPP_TABLE_PROTO or {}
_G.CPP_TABLE_PROTO.Player = {
    name = { type = "normal", key = "string", tag = 1, size = 9, shared = 1 },
    score = { type = "normal", key = "int32", tag = 2, size = 5, shared = 0 },
    is_vip = { type = "normal", key = "bool", tag = 3, size = 2, shared = 0 },
    experience = { type = "normal", key = "float", tag = 4, size = 5, shared = 0 },
    items = { type = "array", key = "Item", tag = 5, size = 9, shared = 1, key_size = 9, key_shared = 1 },
    labels = { type = "array", key = "int32", tag = 6, size = 9, shared = 1, key_size = 5, key_shared = 0 },
    pet = { type = "normal", key = "Pet", tag = 7, size = 9, shared = 1 },
    friends = { type = "map", key = "string", value = "Friend", tag = 8, size = 9, shared = 1 },
    params = { type = "map", key = "int32", value = "int32", tag = 9, size = 9, shared = 1 },
}
_G.CPP_TABLE_PROTO.Item = {
    id = { type = "normal", key = "int64", tag = 1, size = 9, shared = 0 },
    name = { type = "normal", key = "string", tag = 2, size = 9, shared = 1 },
    price = { type = "normal", key = "int32", tag = 3, size = 5, shared = 0 },
    upgrade = { type = "normal", key = "ItemUpgrade", tag = 4, size = 9, shared = 1 },
}
_G.CPP_TABLE_PROTO.ItemUpgrade = {
    cost = { type = "normal", key = "int32", tag = 3, size = 5, shared = 0 },
    level = { type = "normal", key = "int32", tag = 4, size = 5, shared = 0 },
}
_G.CPP_TABLE_PROTO.Pet = {
    name = { type = "normal", key = "string", tag = 1, size = 9, shared = 1 },
    age = { type = "normal", key = "int32", tag = 2, size = 5, shared = 0 },
    breed = { type = "normal", key = "string", tag = 3, size = 9, shared = 1 },
    weight = { type = "normal", key = "double", tag = 4, size = 9, shared = 0 },
    is_vaccinated = { type = "array", key = "bool", tag = 5, size = 9, shared = 1, key_size = 2, key_shared = 0 },
}
_G.CPP_TABLE_PROTO.Friend = {
    name = { type = "normal", key = "string", tag = 1, size = 9, shared = 1 },
    age = { type = "normal", key = "int32", tag = 2, size = 5, shared = 0 },
    email = { type = "normal", key = "string", tag = 3, size = 9, shared = 1 },
}
_G.CPP_TABLE_PROTO.Res2Cnt = {
    cnts = { type = "map", key = "int64", value = "CntInfo", tag = 1, size = 9, shared = 1 },
}
_G.CPP_TABLE_PROTO.CntInfo = {
    permanent = { type = "normal", key = "int32", tag = 1, size = 5, shared = 0 },
    timing = { type = "normal", key = "int32", tag = 2, size = 5, shared = 0 },
    all = { type = "normal", key = "int32", tag = 3, size = 5, shared = 0 },
}
_G.CPP_TABLE_PROTO.SimpleStruct = {
    a = { type = "normal", key = "int32", tag = 1, size = 5, shared = 0 },
    b = { type = "normal", key = "int32", tag = 2, size = 5, shared = 0 },
    c = { type = "normal", key = "int32", tag = 3, size = 5, shared = 0 },
    d = { type = "normal", key = "int32", tag = 4, size = 5, shared = 0 },
    e = { type = "normal", key = "int32", tag = 5, size = 5, shared = 0 },
    f = { type = "normal", key = "int32", tag = 6, size = 5, shared = 0 },
    g = { type = "normal", key = "int32", tag = 7, size = 5, shared = 0 },
    h = { type = "normal", key = "int32", tag = 8, size = 5, shared = 0 },
    i = { type = "normal", key = "int32", tag = 9, size = 5, shared = 0 },
    j = { type = "normal", key = "int32", tag = 10, size = 5, shared = 0 },
    k = { type = "normal", key = "int32", tag = 11, size = 5, shared = 0 },
    l = { type = "normal", key = "int32", tag = 12, size = 5, shared = 0 },
    m = { type = "normal", key = "int32", tag = 13, size = 5, shared = 0 },
    n = { type = "normal", key = "int32", tag = 14, size = 5, shared = 0 },
    o = { type = "normal", key = "int32", tag = 15, size = 5, shared = 0 },
    p = { type = "normal", key = "int32", tag = 16, size = 5, shared = 0 },
    q = { type = "normal", key = "int32", tag = 17, size = 5, shared = 0 },
    r = { type = "normal", key = "int32", tag = 18, size = 5, shared = 0 },
    s = { type = "normal", key = "int32", tag = 19, size = 5, shared = 0 },
    t = { type = "normal", key = "int32", tag = 20, size = 5, shared = 0 },
    u = { type = "normal", key = "int32", tag = 21, size = 5, shared = 0 },
    v = { type = "normal", key = "int32", tag = 22, size = 5, shared = 0 },
    w = { type = "normal", key = "int32", tag = 23, size = 5, shared = 0 },
    x = { type = "normal", key = "int32", tag = 24, size = 5, shared = 0 },
    y = { type = "normal", key = "int32", tag = 25, size = 5, shared = 0 },
    z = { type = "normal", key = "int32", tag = 26, size = 5, shared = 0 },
}
